### ISSUE TITLE
Crash when changing fullscreen mode

### ISSUE THREAD

**Issue by MCMic** [SimonLarsen/mrrescue#13]
Not sure how to trigger the crash but I had one when in the settings and changing fullscreen, saying the game called toggleFullscreen which does not exists.
I did not get the crash again when retrying to change fullscreen mode.

Maybe it was linked to having a config file from a previous version of mrrescue or something.

But there is indeed a call to toggleFullscreen in options.lua which does not seem to exists.

**Comment by judgedreads** [comment]
I can recreate this crash by pressing "jump" on the "fullscreen" option (rather than changing the type of fullscreen with the "right" and "left" actions). This appears to be an artefact from when the "fullscreen" option was boolean. The relevant logic is in lines 166-168 of options.lua, removing these lines should fix the issue. I'm willing to submit a PR for this.

**Comment by SimonLarsen** [comment]
Thank you for reporting this. A PR is not necessary as it is trivial to fix. :)

**Comment by SimonLarsen** [comment]
Fixed
